name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment using .nvmrc
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'  # 确保你项目中有正确的 .nvmrc 文件

      # Install pnpm globally via npm
      - name: Install pnpm
        run: npm install -g pnpm

      # Check pnpm version to verify installation
      - name: Check pnpm version
        run: pnpm --version

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Build the project
      - name: Build the project
        run: pnpm build

  deploy:
    needs: build  # 确保只有在构建成功后才执行部署
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code again in the deploy step
      - name: Checkout code
        uses: actions/checkout@v3

      # Debugging environment variables
      - name: Debugging server connection
        run: |
          echo "SERVER_HOST: $SERVER_HOST"
          echo "SERVER_USER: $SERVER_USER"
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}  

      # Deploy to the server via SSH
      - name: Deploy to Server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          # 使用 scp 将文件传输到 Windows 服务器的指定目录
          scp -i private_key -o StrictHostKeyChecking=no -r dist/* $SERVER_USER@$SERVER_HOST:/C:/website/admin
          # 在 Windows 服务器上通过 PowerShell 重启 Nginx
          ssh -i private_key $SERVER_USER@$SERVER_HOST 'powershell.exe "Restart-Service -Name nginx"'
          rm private_key
