name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment using .nvmrc
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      # Install pnpm globally via npm
      - name: Install pnpm
        run: npm install -g pnpm

      # Check pnpm version to verify installation
      - name: Check pnpm version
        run: pnpm --version

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Build the project
      - name: Build the project
        run: pnpm build

      - name: List output files
        run: ls -alh dist 

      # 上传 dist 目录作为 artifact
      - name: Upload dist directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载 dist 目录
      - name: Download dist directory
        uses: actions/download-artifact@v3
        with:
          name: dist

      # 列出当前目录结构，检查 dist 是否成功下载
      - name: List current directory
        run: ls -alh

      - name: Debugging server connection
        run: |
          echo "SERVER_HOST: $SERVER_HOST"
          echo "SERVER_USER: $SERVER_USER"
          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # 使用 scp 部署文件
      - name: Deploy to Server via SCP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          # 列出 dist 目录内容，确保文件存在
          ls -alh ./dist
          # 使用 scp 传输 dist 目录到服务器
          scp -i private_key -o StrictHostKeyChecking=no -r ./dist/* $SERVER_USER@$SERVER_HOST:"C:/website/admin"
          # 重启 Nginx 服务
          ssh -i private_key $SERVER_USER@$SERVER_HOST 'powershell.exe "Restart-Service -Name nginx"'
          rm private_key

