jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server via SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r dist/* $SERVER_USER@$SERVER_HOST:/C:/website/admin
        ssh -i private_key -o PreferredAuthentications=publickey $SERVER_USER@$SERVER_HOST 'powershell.exe "Restart-Service -Name nginx"'
        rm private_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
